### ISSUE TITLE
Errors in Console With Latest AE

### ISSUE THREAD

**Issue by Devillion** [N3kas/AdvancedEnchantments#39]
I'm gettting these errors: https://pastebin.com/EiDNrKmm

https://pastebin.com/nNSFgeau
https://pastebin.com/V08E8fby

This is also spamming my console over and over https://pastebin.com/jVXp64dj

**Comment by N3kas** [comment]
I've found a config mistake in new updated configuration: http://prntscr.com/k018vk
"REGENERATION" is posted as an effect whilst it's an argument for "POTION:<potion type>" effect. Just add "POTION:" before regeneration and that should fix all errors expect the last link, which points to an issue with sounds. It explains that it couldn't find such sound since a lot of sound names were changed in 1.8-1.12 so most won't match, you have to change those sounds in enchantments.yml as well to fit your server version.
